name: Release

on:
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: '3.10'

jobs:
  build-python:
    name: Build Python Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build wheel

    - name: Build distribution
      run: python -m build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: python-dist
        path: dist/

  build-macos-hud:
    name: Build macOS HUD
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Build HUD for ${{ matrix.arch }}
      run: |
        cd apps/hud-macos
        swift build --configuration release --arch ${{ matrix.arch }}

        # Create app bundle
        mkdir -p GlideHUD.app/Contents/MacOS
        cp .build/release/GlideHUD GlideHUD.app/Contents/MacOS/
        cp Info.plist GlideHUD.app/Contents/

        # Create DMG
        hdiutil create -volname "GlideHUD" -srcfolder GlideHUD.app -ov -format UDZO GlideHUD-${{ matrix.arch }}.dmg

    - name: Upload HUD
      uses: actions/upload-artifact@v3
      with:
        name: macos-hud-${{ matrix.arch }}
        path: apps/hud-macos/GlideHUD-${{ matrix.arch }}.dmg

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-python, build-macos-hud]

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Extract version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Glide ${{ steps.version.outputs.version }}
        draft: true
        prerelease: ${{ contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'beta') }}
        files: |
          python-dist/*
          macos-hud-x86_64/GlideHUD-x86_64.dmg
          macos-hud-arm64/GlideHUD-arm64.dmg
        body: |
          ## What's Changed

          <!-- Add release notes here -->

          ## Installation

          ### Python Package
          ```bash
          pip install glide-${{ steps.version.outputs.version }}.whl
          ```

          ### macOS HUD
          - Download `GlideHUD-{arch}.dmg` for your architecture
          - Open the DMG and drag GlideHUD to Applications
          - Grant accessibility permissions when prompted

          ## Full Changelog
          https://github.com/${{ github.repository }}/compare/previous...${{ steps.version.outputs.version }}
